language: node_js

node_js:
  - 12

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - npm ci
  - npm test:ci

after_success:
  - npm run coverage
